# Use new trusty images, should yield newer compilers and packages
sudo: required
dist: precise
language: cpp

addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake

before_install:
  - sudo apt-get update -qq

script:
   - mkdir build
   - cd build
   - cmake -DBUILD_TESTS .. && make

notifications:
  email: false
